[package]
name = "vesting"
version = "0.0.1"
edition ='2024.alpha'

[dependencies]
Mgo = { git = "https://github.com/MangoNetworkOs/Mango.git", subdir = "crates/mgo-framework/packages/mgo-framework", rev = "main" }

[addresses]
vesting = "0x0"
